[package]
name = "loaderlz4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz4_flex = { version = "0.9.0", default-features = false }
clap = "2"
crc = "2"